import { Box, Label, View, WebGen } from "webgen/mod.ts";
import { DynaNavigation } from "../../components/nav.ts";
import { RegisterAuthRefresh } from "../_legacy/helper.ts";
import { Footer } from "../shared/footer.ts";
import './flowText.css';
WebGen();
await RegisterAuthRefresh();

View(() => Box(
    ...DynaNavigation("Home"),
    Box(
        Label("Terms of Use", "h2"),

        Label(`BBN Holding Inc., a Mississippi c - corporation(“BBN Holding”, "BBN Music", "BBN", “we”, or “us”) provides access to the BBN website, currently located at bbn.one and all associated websites and subpages, including any and all related mobile applications we may make available(collectively, “Application”), together with all enabled features, functionality and services.These terms and conditions(“Terms”) govern your access and use(as a registered user or otherwise) of the Services.`),
        Label(`By accessing or using the Services in any way, you represent and warrant that you have read, understood, and accept and agree to be bound by these Terms. If you do not agree, you may not access or use the Services. Your use of BBN's distribution services, if applicable, is separately governed by the BBN Music Distribution Agreement, and any of its attachments or addendum, located here (https://bbn.one/p/distribution.html).`),
        Label(`Terms of Access and Use`, "h3"),
        Label(`Subject to these Terms, we grant you a limited, non-exclusive, nontransferable personal license to access and use the Services. By accessing and using the Services, you represent and warrant that you are over eighteen (18) years of age or the applicable age of majority in your jurisdiction, and that you are either an individual acting on your own behalf, or the authorized agent of another individual or business. Your use of the Services as an authorized agent shall not relieve you of personal responsibility for your use of the Services. The rights granted to you by these Terms may be revoked by BBN at any time, in its sole discretion.`),
        Label(`When you download the Application under these Terms you are granted a limited, non-exclusive, non-transferable license to use the Services on a computer, tablet or mobile device that you own or control. If you have accessed or downloaded the Application from any “app” store or distribution platform, such as the Apple App Store or Google Play (“App Provider”), you acknowledge and agree that: (i) these Terms and the license granted herein are between you and us only and we are solely responsible for the Application; (ii) the App Provider has no obligation to furnish any maintenance and support services for the Application; (iii) the App Provider is not responsible for addressing any claims you have or any claims of any third party relating to the Application or your possession and use of the Application; (iv) the App Provider, and its subsidiaries, are third party beneficiaries of these Terms as related to your license of the Application, and that, the App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the Application against you as a third party beneficiary thereof; and (v) you will comply with all applicable third party terms of service when using the Application, including any applicable App Provider terms of service. The Application may automatically download and install updates from time to time. These updates are designed to improve, enhance and further develop the Application and may take the form of bug fixes, enhanced functions, new software modules and new versions.`),
        Label(`Registration and Accounts`, "h3"),
        Label(`In order to use certain features of the Services, you may be required to register for an account (“Account”) with us and provide certain information about yourself as prompted by the Account registration form. You represent and warrant that all required registration information you submit is truthful and accurate, and that you will maintain the accuracy of such information. You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You agree to immediately notify us of any unauthorized use, or suspected unauthorized use of your Account or any other breach of security. We cannot and will not be liable for any loss or damage arising from unauthorized access to your Account or your failure to comply with the above requirements.`),
        Label(`Privacy`, "h3"),
        Label(`For information regarding our collection and use of information you provide to us, please refer to the Services' privacy policy (“Privacy Policy”), located here (https://bbn.one/p/privacy.html) which shall supplement and be incorporated into these Terms by reference. By entering into these Terms, you agree to our collection, use and disclosure of your personal information in accordance with our Privacy Policy.`),
        Label(`User Content and Activity`, "h3"),
        Label(`The features and functionality of the Services may allow users to submit, upload, store and/or share reviews, comments, questions, messages, audio recordings, musical compositions, images, artwork, photographs, audio-visual content, text and other content, information or materials (“User Content”) directly through the Services, and users shall be able to share such User Content using the features made available by the Services from time to time. The functionality of the Services may allow registered users to make certain User Content publicly available for other users (registered or unregistered) to view, listen to and share. Other features of the Services may enable users to privately submit and share messages between users or to upload files to store and share for private use. The foregoing activities described in this paragraph are sometimes collectively referred to herein as “User Activity”.`),
        Label(`You are solely responsible for the User Content you submit through the Services as well as your User Activity generally. You agree that, through our Services and at your direction, we are only acting as a passive conduit for your online distribution, storage, publication and/or other exploitation of your User Content. Between you and BBN, BBN does not claim any ownership rights with respect to your User Content. By uploading, publishing, modifying, displaying or otherwise submitting User Content to any part of the Services, you automatically grant, and you represent and warrant that you have the right to grant, to us, as well as to other users of the Services, a non-exclusive, transferable, fully paid, worldwide license to use, copy, reproduce, publicly perform, publicly display, communicate to the public, stream, listen to, make available, reformat, translate, excerpt (in whole or in part), transmit, re-post and distribute such User Content for any purpose on or in connection with Services.`),
        Label(`Accordingly you represent, warrant and agree that: (a) you have the right to agree to these Terms; (b) all of your User Content is original with you, in the public domain throughout the world or used by you with the express consents, permissions or licenses necessary from the original owner(s) of such materials for use by you and us pursuant to these Terms; (c) your User Content does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights (as defined below) or rights of publicity and privacy; (d) BBN shall not be responsible for payments or any other liability to any third party in connection with the use of your User Content on the Site, Application, Services or otherwise in connection with these Terms; and (e) none of your User Content or Direct Messages contain material which is unlawful, harmful, abusive, racially or ethnically offensive, defamatory, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), libelous, threatening, profane, otherwise objectionable or content that may be deemed to constitute “hate speech”.`),
        Label(`BBN reserves the right to reject and/or remove any User Content, Direct Messages or other content that BBN believes, in its sole discretion, violates these provisions. BBN takes no responsibility and assumes no liability for any User Content and/or Direct Messages that you or any other users or third parties post, use, store or share through the Services. You understand and agree that any loss or damage of any kind that occurs as a result of the use of any User Content or Direct Messages that you send, upload, download, stream, post, transmit, display, or otherwise make available or access through your use of the Services, is solely your responsibility. BBN is not responsible for any public display or misuse of your User Content. You understand and acknowledge that you may be exposed to User Content that is inaccurate, offensive, indecent, or objectionable, and you agree that BBN shall not be liable for any damages you allege to incur as a result of such User Content.`),
        Label(`For the purposes of these Terms, “Intellectual Property Rights” means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.`),
        Label(`Miscellaneous`, "h3"),
        Label(`These Terms and the Privacy Policy constitute the entire agreement between you and us with respect to your access to and use of the Services. We reserve the right to terminate these Terms, your Account, and your access to the Services at any time without notice. You may delete your Account at any time, for any reason, by following the instructions on the Site or Application. Your rights under these Terms will automatically and immediately terminate if you fail to comply with your promises and obligations stated in these Terms. If any provisions hereof are deemed invalid or unenforceable, they will be severed or construed to reflect, as nearly as possible, the original intentions of the parties, and the remaining provisions shall remain in full force and effect. No waiver of any provision by us shall be deemed a further or continuing waiver of such provision or any other provision, and our failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The Services are hosted and operated in the United States of America and we make no representation that any content is appropriate for access outside of the United States. Those who choose to access the Services from outside the United States do so on their own initiative and are responsible for compliance with local laws. These Terms shall be construed and enforced in accordance with the laws of the United States and the State of Mississippi, without regard to any conflict of law provisions, and any and all legal actions in connection with the Site, Service and/or these Terms of Service or our Privacy Policy shall be brought exclusively in the federal or state courts located in Madison County, Mississippi, sU.S.A.`),

    ).addClass("flow-text"),
    Footer()
)).appendOn(document.body);