name: Deplox to Prod

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Update bbn.one
    runs-on: ubuntu-latest

    steps:
      - name: Pull Project
        uses: actions/checkout@v2

      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Building bbn.one
        run: deno run --no-check -A serve.ts production

      - name: Publish to bbn.one
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./dist
          remote: /root/bbn.one
          host: ${{ secrets.WEB_HOST }}
          port: ${{ secrets.WEB_PORT }}
          username: ${{ secrets.WEB_USERNAME }}
          password: ${{ secrets.WEB_PASSWORD }}